#!/usr/bin/env bash

: ${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND='zd --selection'}
: ${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG="QUERY|''"}

export TODOTXT_MOVEELSEWHERE_SOURCE_WHAT='global / current local todo.txt file'
export TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT='local task list in DIR'
export TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL=0
export TODOTXT_MOVEELSEWHERE_DEST_ARG="DIR${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG:+|$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG}"

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

action=$1
shift

[ "$action" = "usage" ] \
    && TODOTXT_MOVEELSEWHERE_ACTION_NAME=movetolocal exec "${scriptDir}/moveelsewhere" usage "$@"

[ $# -gt 0 ] \
    || die 'TODO: Missing target directory.'
targetDir="${1?}"; shift
if [ ! -d "$targetDir" -a -n "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" ]; then
    # Try to resolve the target directory through the lookup command.
    lookedUptargetDir="$(eval "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" "$targetDir")"
    [ -d "$lookedUptargetDir" ] \
	&& targetDir="$lookedUptargetDir" \
	|| die "TODO: Target directory does not exist, and could not look it up: $targetDir"
fi
[ -d "$targetDir" ] \
    || die "TODO: Target directory does not exist: $targetDir"
targetTodoFile="${targetDir%/}/todo.txt"

exec "${scriptDir}/moveelsewhere" "$action" "$targetTodoFile" "$@"
