#!/usr/bin/env bash

: ${TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL:=0}
: ${TODOTXT_MOVEELSEWHERE_DEST_ARG=DEST}

action=$1
shift

[ "$action" = "usage" ] && {
    destArg="$TODOTXT_MOVEELSEWHERE_DEST_ARG"
    case "$TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL" in
	0)  echo "    ${TODOTXT_MOVEELSEWHERE_ACTION_NAME:-$(basename $0)} ${destArg}${destArg:+ }TERM|NR [...]"
	    echo "      Moves tasks that contain TERM(s) (after confirmation) / line(s) NR from"
	    echo "      the ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-current todo.txt file} to the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${destArg}${destArg:+ }task list}."
	    ;;
	1)  echo "    ${TODOTXT_MOVEELSEWHERE_ACTION_NAME:-$(basename $0)} ${destArg}${destArg:+ }[TERM|NR ...]"
	    echo "      Moves all tasks / tasks that contain TERM(s) (after confirmation) /"
	    echo "      line(s) NR from the ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-current todo.txt file} to the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${destArg}${destArg:+ }task list}."
	    ;;
    esac
    echo ""
    exit
}

sourceTodoFile="${TODO_FILE:?}"
[ -s "$sourceTodoFile" ] \
    || die 'TODO: No tasks found.'

[ $# -gt 0 ] \
    || die "TODO: Missing ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${TODOTXT_MOVEELSEWHERE_DEST_ARG}${TODOTXT_MOVEELSEWHERE_DEST_ARG:+ arg}}."
destinationTodoFile="${1:?}"; shift
if [ ! -e "$destinationTodoFile" ]; then
    destinationDir="$(dirname -- "$destinationTodoFile")"
    [ -d "$destinationDir" ] \
	|| die "TODO: The ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-destination}'s directory does not exist: $destinationDir"

    touch -- "$destinationTodoFile" \
	|| exit 1
fi
[ ! "$sourceTodoFile" -ef "$destinationTodoFile" ] \
    || die "TODO: The ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-source} and the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-destination} must not be the same, but are: $sourceTodoFile"
[ $# -gt 0 -o $TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL -ne 0 ] \
    || die 'TODO: Missing TERM(s) or NR(s).'

typeset -a items=()
while [[ "$1" =~ ^[0-9]+$ ]]
do
    item=$1
    getTodo "$item" "$sourceTodoFile"
    items+=("$item"); shift
done
if [ ${#items[@]} -gt 0 -a $# -gt 0 ]; then
    die 'TODO: Cannot pass both NR and TERM(s) at the same time.'
fi

didMoveItems=
if [ ${#items[@]} -eq 0 ]; then
    # Consider only tasks that are not yet done, but don't let custom filters hide
    # any tasks (like future tasks).
    exec 3>&1
	taskList="$(
	    post_filter_command="grep -ve '^ *[0-9]\+ [xX] '" \
	    TODOTXT_FILTER_HIDE_TASKS=0 \
		_list "$sourceTodoFile" "$@" \
		    | tee /dev/fd/3
	)"
    exec 3>&-
    < <(printf '%s\n' "$taskList" | "$TODO_FULL_SH" tasks) read -r -a items
    [ ${#items[@]} -gt 0 ] || die 'TODO: No matching tasks found.'

    read -rp "Move these task(s) to ${destinationTodoFile}? (y/n) " answer
    [ "$answer" = 'y' ] || exit 0

    # Optimization: Move the entire file en block.
    if [ $# -eq 0 ]; then
	cat -- "$sourceTodoFile" >> "$destinationTodoFile" \
	    && rm -- "$sourceTodoFile" \
	    || die 'TODO: Error moving all tasks.'
	didMoveItems=t	# Skip the individual move (but not the message); all tasks have already been moved.
    fi
fi

if [ ! "$didMoveItems" ]; then
    sedItemMoveCommand="$(cat <<'EOF'
{
    w /dev/stdout
    s/.*//
}
EOF
    )"
    IFS=$'\n'; moveSedScript="${items[*]/%/"$sedItemMoveCommand"}"
    sed -i.bak -e "$moveSedScript" -- "$sourceTodoFile" >> "$destinationTodoFile" \
	|| die 'TODO: Error moving tasks.'
fi

# Show the tail of the destination todo.txt file with the moved tasks.
TODOTXT_SORT_COMMAND="tail -n ${#items[@]}" \
TODOTXT_FILTER_HIDE_TASKS=0 \
    _list "$destinationTodoFile" "$@" \
