#!/usr/bin/env bash
set -o pipefail
shopt -qs extglob

: ${TODOTXT_MOVETOLOCAL_DIR_EXTRACTOR_COMMAND='todo-local-project --to-dir'}
: ${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND='zd --selection'}
: ${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG="QUERY|''"}

# Duplicated to ./movetoglobal
# Shell command that is executed inside each local todo.txt file's directory
# when moving tasks. Each output line is prepended / appended to the task text
# after moving it to the global todo.txt file, providing explicit information
# (like a +project) that previously was implicitly stored in the local todo.txt
# file location.
# Likewise, when moving tasks from the global todo.txt file to a local todo.txt
# file, each output line is treated as literal whitespace-delimited text that
# is removed from the task text after moving it to the local todo.txt file,
# dropping the explicit information (like a +project) that is now implicitly
# stored in the local todo.txt file location.
: ${TODOTXT_LOCAL_ORIGIN_COMMAND='todo-local-project --to-origin'}
: ${TODOTXT_LOCAL_ORIGIN_INSERTION_ACTION:='prepend'}

export TODOTXT_MOVEELSEWHERE_SOURCE_WHAT='global / current local todo.txt file'
export TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT='local task list in DIR'
export TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL=0
if [ -n "$TODOTXT_MOVETOLOCAL_DIR_EXTRACTOR_COMMAND" ]; then
    export TODOTXT_MOVEELSEWHERE_DEST_ARG="[DIR${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG:+|-q|--query $TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG}]"
else
    export TODOTXT_MOVEELSEWHERE_DEST_ARG="DIR${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG:+|$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG}"
fi

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

action=$1
shift

targetDir=

extractTargetDir()
{
    targetDir="$(
	TODOTXT_MOVEELSEWHERE_LIST_SOURCE_TASKS_ONLY=t "${scriptDir}/moveelsewhere" "$action" "$@" \
	    | eval "$TODOTXT_MOVETOLOCAL_DIR_EXTRACTOR_COMMAND"
	exit ${PIPESTATUS[0]}	# Ignore the exit status of the extractor; what counts is [the validity of] its output.
    )" || exit $?   # A failure comes from moveelsewhere, and in that case an error message was already given.

    # Check if the extractor actually delivered, and complain if not.
    if [ ! -d "$targetDir" ]; then
	mandatoryDestArg="${TODOTXT_MOVEELSEWHERE_DEST_ARG#\[}"; mandatoryDestArg="${mandatoryDestArg%\]}"
	die "TODO: Could not extract the target directory from the to-be-moved tasks; you need to pass ${mandatoryDestArg}"
    fi
}

lookupTargetDir()
{
    local query="${1?}"; shift
    # Try to resolve the target directory through the lookup command.
    targetDir="$(eval "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" "$query")"
    [ -d "$targetDir" ] \
	|| die "TODO: Target directory does not exist, and could not look it up: $query"
}

[ "$action" = "usage" ] \
    && TODOTXT_MOVEELSEWHERE_ACTION_NAME=movetolocal exec "${scriptDir}/moveelsewhere" usage "$@"

if [ -d "$1" ]; then
    targetDir="${1?}"; shift
elif [ -n "$TODOTXT_MOVETOLOCAL_DIR_EXTRACTOR_COMMAND" -a -n "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" ] && [[ "$1" = @(--query|-q) ]]; then
    shift
    [ $# -gt 0 ] || die "TODO: Missing $TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG"
    lookupTargetDir "${1?}"; shift
elif [ -n "$TODOTXT_MOVETOLOCAL_DIR_EXTRACTOR_COMMAND" ]; then
    extractTargetDir "$@"
elif [ -n "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" ]; then
    [ $# -gt 0 ] || die "TODO: Missing $TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG"
    lookupTargetDir "${1?}"; shift
elif [ $# -eq 0 ]; then
    die 'TODO: Missing target directory.'
fi
[ -d "$targetDir" ] \
    || die "TODO: Target directory does not exist: $targetDir"
targetTodoFile="${targetDir%/}/todo.txt"

if [ -n "$TODOTXT_LOCAL_ORIGIN_COMMAND" ]; then
    # Remove the local origin(s) from the task text after moving it to its local
    # todo.txt file.
    printf -v quotedTodoDir %q "${targetDir:?}"
    quotedSubstArgs=
    while IFS=$'\n' read -r origin || { exitStatus="$origin"; break; }	# Exit status from the process substitution is lost; return the actual exit status via an incomplete (i.e. missing the newline) last line.
    do
	literalOrigin="$(toLiteralRegexp "$origin")"
	printf -v quotedSubstArgs "%s' '%q'\\(\$\| \\)' ' '" "${quotedSubstArgs}${quotedSubstArgs:+ }" "$literalOrigin"
    done < <(eval "$TODOTXT_LOCAL_ORIGIN_COMMAND $quotedTodoDir"; printf %d "$?")

    if [ $exitStatus -eq 0 -a -n "$quotedSubstArgs" ]; then
	# Use subst instead of del|rm because it handles multiple NRs and thereby
	# doesn't complain if some tasks don't match (and also handles multiple
	# TERM(s)). Ignore even when no removals were made.
	export TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION="subst {@} $quotedSubstArgs || :"
    fi
fi

exec "${scriptDir}/moveelsewhere" "$action" "$targetTodoFile" "$@"
