#!/usr/bin/env bash

: ${TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL:=0}
: ${TODOTXT_MOVEELSEWHERE_DEST_ARG=DEST}

: ${TODOTXT_MOVEELSEWHERE_NR_MARKER='{}'}   # Replaced with NR; TODOTXT_MOVEELSEWHERE_{PRE,POST}MOVE_ACTION is then executed for each task individually.
: ${TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER='{@}'}	# Replaced with all NR(s); TODOTXT_MOVEELSEWHERE_{PRE,POST}MOVE_ACTION is then executed once for all task(s).
nrMarker="$TODOTXT_MOVEELSEWHERE_NR_MARKER"; unset TODOTXT_MOVEELSEWHERE_NR_MARKER
allNrsMarker="$TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER"; unset TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER
: ${TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION=}
: ${TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION=}

action=$1
shift

[ "$action" = "usage" ] && {
    destArg="$TODOTXT_MOVEELSEWHERE_DEST_ARG"
    case "$TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL" in
	0)  echo "    ${TODOTXT_MOVEELSEWHERE_ACTION_NAME:-$(basename $0)} ${destArg}${destArg:+ }TERM|NR [...]"
	    echo "      Moves tasks that contain TERM(s) (after confirmation) / line(s) NR from"
	    echo "      the ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-current todo.txt file} to the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${destArg}${destArg:+ }task list}."
	    ;;
	1)  echo "    ${TODOTXT_MOVEELSEWHERE_ACTION_NAME:-$(basename $0)} ${destArg}${destArg:+ }[TERM|NR ...]"
	    echo "      Moves all tasks / tasks that contain TERM(s) (after confirmation) /"
	    echo "      line(s) NR from the ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-current todo.txt file} to the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${destArg}${destArg:+ }task list}."
	    ;;
    esac
    echo ""
    exit
}

runInterpolatedAction()
{
    local quotedLauncher; printf -v quotedLauncher %q "${1:?}"; shift
    local originalAction="${1:?}"; shift

    local quotedItems interpolatedAction="$originalAction"
    printf -v quotedItems '%q ' "$@"; quotedItems="${quotedItems% }"
    interpolatedAction="${interpolatedAction//"$allNrsMarker"/$quotedItems}"
    if [ "$interpolatedAction" = "$originalAction" ]; then
	# No TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER marker; run the action for each task
	# individually and interpolate TODOTXT_MOVEELSEWHERE_NR_MARKER or append each
	# NR.
	local item quotedItem status
	for item
	do
	    interpolatedAction="$originalAction"
	    printf -v quotedItem %q "$item"
	    interpolatedAction="${interpolatedAction//"$nrMarker"/$quotedItem}"
	    [ "$interpolatedAction" = "$originalAction" ] || quotedItem=''
	    eval "$quotedLauncher $interpolatedAction $quotedItem" || status=$?
	done
	return ${status:-0}
    else
	# TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER has been interpolated; run the action
	# once for all tasks.
	eval "$quotedLauncher $interpolatedAction"
    fi
}

runPreMoveAction()
{
    runInterpolatedAction "$TODO_FULL_SH" "$TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION" "$@"
}

runPostMoveAction()
(
    local destinationDir="$(dirname -- "$destinationTodoFile")"
    cd "$destinationDir" || die "TODO: Cannot change to destination directory: $destinationDir"
    unset TODO_DIR TODO_FILE	# So that todo-local.sh doesn't pick up the source environment.

    runInterpolatedAction todo-local.sh "$TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION" "$@"
)

sourceTodoFile="${TODO_FILE:?}"
[ -s "$sourceTodoFile" ] \
    || die 'TODO: No tasks found.'

[ $# -gt 0 ] \
    || die "TODO: Missing ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${TODOTXT_MOVEELSEWHERE_DEST_ARG}${TODOTXT_MOVEELSEWHERE_DEST_ARG:+ arg}}."
destinationTodoFile="${1:?}"; shift
if [ ! -e "$destinationTodoFile" ]; then
    destinationDir="$(dirname -- "$destinationTodoFile")"
    [ -d "$destinationDir" ] \
	|| die "TODO: The ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-destination}'s directory does not exist: $destinationDir"

    touch -- "$destinationTodoFile" \
	|| exit 1
fi
[ ! "$sourceTodoFile" -ef "$destinationTodoFile" ] \
    || die "TODO: The ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-source} and the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-destination} must not be the same, but are: $sourceTodoFile"
[ $# -gt 0 -o $TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL -ne 0 ] \
    || die 'TODO: Missing TERM(s) or NR(s).'

typeset -a items=()
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    for item in ${1//,/ }
    do
	getTodo "$item" "$sourceTodoFile"
	items+=("$item"); shift
    done
done
if [ ${#items[@]} -gt 0 -a $# -gt 0 ]; then
    die 'TODO: Cannot pass both NR and TERM(s) at the same time.'
fi

didMoveItems=
if [ ${#items[@]} -eq 0 ]; then
    # Consider only tasks that are not yet done, but don't let custom filters hide
    # any tasks (like future tasks).
    exec 3>&1
	taskList="$(
	    post_filter_command="grep -ve '^ *[0-9]\+ [xX] '" \
	    TODOTXT_FILTER_HIDE_TASKS=0 \
	    TODOTXT_SORT_COMMAND=cat \
		_list "$sourceTodoFile" "$@" \
		    | tee /dev/fd/3
	)"
    exec 3>&-
    < <(printf '%s\n' "$taskList" | "$TODO_FULL_SH" tasks) read -r -a items
    [ ${#items[@]} -gt 0 ] || die 'TODO: No matching tasks found.'

    read -rp "Move these task(s) to ${destinationTodoFile}? (y/n) " answer
    [ "$answer" = 'y' ] || exit 0

    [ -z "$TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION" ] \
	|| runPreMoveAction "${items[@]}" \
	|| die 'TODO: Error running pre-move action.'

    # Optimization: Move the entire file en block.
    if [ $# -eq 0 ]; then
	cat -- "$sourceTodoFile" >> "$destinationTodoFile" \
	    && rm -- "$sourceTodoFile" \
	    || die 'TODO: Error moving all tasks.'
	didMoveItems=t	# Skip the individual move (but not the message); all tasks have already been moved.
    fi
fi

if [ ! "$didMoveItems" ]; then
    [ -z "$TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION" ] \
	|| runPreMoveAction "${items[@]}" \
	|| die 'TODO: Error running pre-move action.'

    sedItemMoveAction="$(cat <<'EOF'
{
    w /dev/stdout
    s/.*//
}
EOF
    )"
    IFS=$'\n'; moveSedScript="${items[*]/%/"$sedItemMoveAction"}"
    sed -i.bak -e "$moveSedScript" -- "$sourceTodoFile" >> "$destinationTodoFile" \
	|| die 'TODO: Error moving tasks.'
fi

unset status
if [ -n "$TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION" ]; then
    < <(
	TODOTXT_SORT_COMMAND="tail -n ${#items[@]}" \
	TODOTXT_FILTER_HIDE_TASKS=0 \
	    _list "$destinationTodoFile" \
		| "$TODO_FULL_SH" tasks
    ) read -r -a postMoveItems
    runPostMoveAction "${postMoveItems[@]}" \
	|| { echo >&2 'TODO: Error running post-move action.'; status=1; }	# Don't die, we still want to show the moved tasks (even though they didn't get (fully) processed by the post-move action).
fi

# Show the tail of the destination todo.txt file with the moved tasks.
TODOTXT_SORT_COMMAND="tail -n ${#items[@]}" \
TODOTXT_FILTER_HIDE_TASKS=0 \
    _list "$destinationTodoFile"
exit $status
