#!/usr/bin/env bash

: ${TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL:=0}
: ${TODOTXT_MOVEELSEWHERE_DEST_ARG=DEST}

: ${TODOTXT_MOVEELSEWHERE_NR_MARKER='{}'}   # Replaced with NR; TODOTXT_MOVEELSEWHERE_{PRE,POST}MOVE_ACTION is then executed for each task individually.
: ${TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER='{@}'}	# Replaced with all NR(s); TODOTXT_MOVEELSEWHERE_{PRE,POST}MOVE_ACTION is then executed once for all task(s).
nrMarker="$TODOTXT_MOVEELSEWHERE_NR_MARKER"; unset TODOTXT_MOVEELSEWHERE_NR_MARKER
allNrsMarker="$TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER"; unset TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER
: ${TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION=}
: ${TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION2=}
: ${TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION=}
: ${TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION2=}

action=$1
shift

[ "$action" = "usage" ] && {
    destArg="$TODOTXT_MOVEELSEWHERE_DEST_ARG"
    case "$TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL" in
	0)  echo "    ${TODOTXT_MOVEELSEWHERE_ACTION_NAME:-$(basename $0)} ${destArg}${destArg:+ }TERM|NR [...]"
	    echo "      Moves tasks that contain TERM(s) (after confirmation) / line(s) NR from"
	    echo "      the ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-current todo.txt file} to the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${destArg}${destArg:+ }task list}."
	    ;;
	1)  echo "    ${TODOTXT_MOVEELSEWHERE_ACTION_NAME:-$(basename $0)} ${destArg}${destArg:+ }[TERM|NR ...]"
	    echo "      Moves all tasks / tasks that contain TERM(s) (after confirmation) /"
	    echo "      line(s) NR from the ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-current todo.txt file} to the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${destArg}${destArg:+ }task list}."
	    ;;
    esac
    [ -z "$TODOTXT_MOVEELSEWHERE_ADDITIONAL_USAGE" ] || echo "$TODOTXT_MOVEELSEWHERE_ADDITIONAL_USAGE"
    echo ""
    exit
}

sourceTodoFile="${TODO_FILE:?}"
[ -s "$sourceTodoFile" ] \
    || die 'TODO: No tasks found.'

listSourceTasks()
{
    # Consider only tasks that are not yet done, but don't let custom filters hide
    # any tasks (like future tasks).
    post_filter_command="grep -ve '^ *[0-9]\+ [xX] '" \
    TODOTXT_FILTER_HIDE_TASKS=0 \
    TODOTXT_SORT_COMMAND=cat \
	_list "$sourceTodoFile" "$@"
}

listSourceTasksAsAPreview()
{
    if [ ${#items[@]} -eq 0 ]; then
	if [ $# -eq 0 ]; then
	    # Optimization: Print the entire file en block.
	    cat -- "$sourceTodoFile"
	else
	    # Filter by TERM(s).
	    TODOTXT_PLAIN=1 TODOTXT_VERBOSE=0 listSourceTasks "$@"
	fi
    else
	# Select passed NR(s).
	local IFS=$'\n'; local listSedScript="${items[*]/%/p}"
	sed -n -e "$listSedScript" -- "$sourceTodoFile"
    fi
}

ensureDestinationTodoFile()
{
    if [ ! -e "$destinationTodoFile" ]; then
	destinationDir="$(dirname -- "$destinationTodoFile")"
	[ -d "$destinationDir" ] \
	    || die "TODO: The ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-destination}'s directory does not exist: $destinationDir"

	touch -- "$destinationTodoFile" \
	    || exit 1
    fi
    [ ! "$sourceTodoFile" -ef "$destinationTodoFile" ] \
	|| die "TODO: The ${TODOTXT_MOVEELSEWHERE_SOURCE_WHAT:-source} and the ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-destination} must not be the same, but are: $sourceTodoFile"
}

runInterpolatedAction()
{
    local quotedLauncher; printf -v quotedLauncher %q "${1:?}"; shift
    local originalAction="${1:?}"; shift

    local quotedItems interpolatedAction="$originalAction"
    printf -v quotedItems '%q ' "$@"; quotedItems="${quotedItems% }"
    interpolatedAction="${interpolatedAction//"$allNrsMarker"/$quotedItems}"
    if [ "$interpolatedAction" = "$originalAction" ]; then
	# No TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER marker; run the action for each task
	# individually and interpolate TODOTXT_MOVEELSEWHERE_NR_MARKER or append each
	# NR.
	local item quotedItem status
	for item
	do
	    interpolatedAction="$originalAction"
	    printf -v quotedItem %q "$item"
	    interpolatedAction="${interpolatedAction//"$nrMarker"/$quotedItem}"
	    [ "$interpolatedAction" = "$originalAction" ] || quotedItem=''
	    eval "$quotedLauncher $interpolatedAction $quotedItem" || status=$?
	done
	return ${status:-0}
    else
	# TODOTXT_MOVEELSEWHERE_ALL_NRS_MARKER has been interpolated; run the action
	# once for all tasks.
	eval "$quotedLauncher $interpolatedAction"
    fi
}

runPreMoveActions()
{
    local action; for action in "$TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION" "$TODOTXT_MOVEELSEWHERE_PREMOVE_ACTION2"
    do
	[ -z "$action" ] || runInterpolatedAction "$TODO_FULL_SH" "$action" "$@" || return $?
    done
}

runPostMoveActions()
(
    local destinationDir="$(dirname -- "$destinationTodoFile")"
    cd "$destinationDir" || die "TODO: Cannot change to destination directory: $destinationDir"
    unset TODO_DIR TODO_FILE	# So that todo-local.sh doesn't pick up the source environment.

    local action; for action in "$TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION" "$TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION2"
    do
	[ -z "$action" ] || runInterpolatedAction todo-local.sh "$action" "$@" || return $?
    done
)

move()
{
    local didMoveItems=
    if [ ${#items[@]} -eq 0 ]; then
	# List tasks, optionally filtered by TERM(s).
	exec 3>&1
	    local taskList="$(listSourceTasks "$@" | tee /dev/fd/3)"
	exec 3>&-
	< <(printf '%s\n' "$taskList" | "$TODO_FULL_SH" tasks) read -r -a items
	[ ${#items[@]} -gt 0 ] || die 'TODO: No matching tasks found.'

	local answer; read -rp "Move these task(s) to ${destinationTodoFile}? (y/n) " answer
	[ "$answer" = 'y' ] || exit 0

	runPreMoveActions "${items[@]}" \
	    || die 'TODO: Error running pre-move action.'

	# Optimization: Move the entire file en block.
	if [ $# -eq 0 ]; then
	    cat -- "$sourceTodoFile" >> "$destinationTodoFile" \
		&& rm -- "$sourceTodoFile" \
		|| die 'TODO: Error moving all tasks.'
	    didMoveItems=t	# Skip the individual move (but not the message); all tasks have already been moved.
	fi
    fi

    if [ ! "$didMoveItems" ]; then
	runPreMoveActions "${items[@]}" \
	    || die 'TODO: Error running pre-move action.'

	# Move passed / resolved NR(s).
	sedItemMoveAction="$(cat <<'EOF'
{
    w /dev/stdout
    s/.*//
}
EOF
	)"
	local IFS=$'\n'; local moveSedScript="${items[*]/%/"$sedItemMoveAction"}"
	sed -i.bak -e "$moveSedScript" -- "$sourceTodoFile" >> "$destinationTodoFile" \
	    || die 'TODO: Error moving tasks.'
    fi

    unset status
    if [ -n "$TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION" -o -n "$TODOTXT_MOVEELSEWHERE_POSTMOVE_ACTION2" ]; then
	typeset -a postMoveItems=()
	read -r -a postMoveItems < <(
	    TODOTXT_SORT_COMMAND="tail -n ${#items[@]}" \
	    TODOTXT_FILTER_HIDE_TASKS=0 \
		_list "$destinationTodoFile" \
		    | "$TODO_FULL_SH" tasks
	)
	runPostMoveActions "${postMoveItems[@]}" \
	    || { echo >&2 'TODO: Error running post-move action.'; status=1; }	# Don't die, we still want to show the moved tasks (even though they didn't get (fully) processed by the post-move action).
    fi

    # Show the tail of the destination todo.txt file with the moved tasks.
    TODOTXT_SORT_COMMAND="tail -n ${#items[@]}" \
    TODOTXT_FILTER_HIDE_TASKS=0 \
	_list "$destinationTodoFile"
    return $status
}

action=move
if [ -n "$TODOTXT_MOVEELSEWHERE_LIST_SOURCE_TASKS_ONLY" ]; then
    action=listSourceTasksAsAPreview
else
    # DEST is directly passed.
    [ $# -gt 0 ] \
	|| die "TODO: Missing ${TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT:-${TODOTXT_MOVEELSEWHERE_DEST_ARG}${TODOTXT_MOVEELSEWHERE_DEST_ARG:+ arg}}."
    destinationTodoFile="${1:?}"; shift
    ensureDestinationTodoFile
fi

[ $# -gt 0 -o $TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL -ne 0 ] \
    || die 'TODO: Missing TERM(s) or NR(s).'

typeset -a items=()
while [[ "$1" =~ ^[,0-9]+$ ]]
do
    for item in ${1//,/ }
    do
	getTodo "$item" "$sourceTodoFile"
	items+=("$item"); shift
    done
done
if [ ${#items[@]} -gt 0 -a $# -gt 0 ]; then
    die 'TODO: Cannot pass both NR and TERM(s) at the same time.'
fi

$action "$@"
